### ISSUE TITLE
Index error when adding new dataset

### ISSUE THREAD

**Issue by belisards** [alephdata/aleph#1056]
Hi, now I can run Aleph but I am having issues to include new datasets.

If I try via the web interface, I receive this error: `"no such index [aleph-entity-message-v1]"`

Via CLI I got this:

```
root@aleph:/aleph/contrib# aleph crawldir testdata               
[2020-03-17 03:54:24,455] WARNING:elasticsearch:GET http://elasticsearch:9200/aleph-entity-useraccount-v1,aleph-entity-package-v1,aleph-entity-plaintext-v1,aleph-entity-event-v1,aleph-entity-company-v1,aleph-entity-vessel-v1,aleph-entity-pages-v1,aleph-entity-audio-v1,aleph-entity-contract-v1,aleph-entity-hypertext-v1,aleph-entity-vehicle-v1,aleph-entity-folder-v1,aleph-entity-email-v1,aleph-entity-video-v1,aleph-entity-asset-v1,aleph-entity-organization-v1,aleph-entity-publicbody-v1,aleph-entity-license-v1,aleph-entity-land-v1,aleph-entity-workbook-v1,aleph-entity-document-v1,aleph-entity-realestate-v1,aleph-entity-legalentity-v1,aleph-entity-bankaccount-v1,aleph-entity-assessment-v1,aleph-entity-image-v1,aleph-entity-courtcase-v1,aleph-entity-table-v1,aleph-entity-person-v1,aleph-entity-airplane-v1,aleph-entity-message-v1/_search?timeout=20m [status:404 request:0.010s]
Traceback (most recent call last):
  File "/usr/local/bin/aleph", line 11, in <module>
    load_entry_point('aleph', 'console_scripts', 'aleph')()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/aleph/aleph/manage.py", line 90, in crawldir
    collection = ensure_collection(foreign_id, path.name)
  File "/aleph/aleph/manage.py", line 52, in ensure_collection
    create_collection(config, authz)
  File "/aleph/aleph/logic/collections.py", line 27, in create_collection
    return update_collection(collection, sync=sync)
  File "/aleph/aleph/logic/collections.py", line 34, in update_collection
    return index.index_collection(collection, sync=sync)
  File "/aleph/aleph/index/collections.py", line 87, in index_collection
    data = get_collection(collection.id)
  File "/aleph/aleph/index/collections.py", line 115, in get_collection
    schemata = get_facet_values(collection.id, 'schema')
  File "/aleph/aleph/index/collections.py", line 153, in get_facet_values
    timeout='20m')
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch/client/__init__.py", line 1548, in search
    "GET", _make_path(index, doc_type, "_search"), params=params, body=body
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 261, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [aleph-entity-useraccount-v1]', aleph-entity-useraccount-v1, index_or_alias)

```

**Comment by pudo** [comment]
I think you need to migrate the database and search index to `3.6.0` using `make upgrade` (or `aleph upgrade` inside a docker env).
