### ISSUE TITLE
Ingesting ODS spreadsheets throws an exception

### ISSUE THREAD

**Issue by critocrito** [alephdata/aleph#1060]
I tried to find the file that throws the exception but I couldn't find a file named `Obrazac ponude KM OS LAZA K.LAZAREVIC.ods` using `find`. How can I read the log output to find the file that is responsible for throwing the exception?

I get this type of exception often and it crashes the ingestors. 

```
Mar 18 08:37:39 fish ingestors[29798]: DEBUG:ingestors.worker:Ingest: <E('142761811963063d4e30ea0dafd50748d82824b9','Obrazac ponude KM OS LAZA K.LAZAREVIC.ods')>
Mar 18 08:37:39 fish ingestors[29798]: INFO:ingestors.manager:Ingestor [<E('142761811963063d4e30ea0dafd50748d82824b9','Obrazac ponude KM OS LAZA K.LAZAREVIC.ods')>]: OpenOfficeSpreadsheetIngestor
Mar 18 08:37:39 fish ingestors[29798]: WARNING:servicelayer.worker:Queue failed task for re-try...
Mar 18 08:37:39 fish ingestors[29798]: Exception in thread Thread-1:
Mar 18 08:37:39 fish ingestors[29798]: Traceback (most recent call last):
Mar 18 08:37:39 fish ingestors[29798]:   File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
Mar 18 08:37:39 fish ingestors[29798]:     self.run()
Mar 18 08:37:39 fish ingestors[29798]:   File "/usr/lib/python3.7/threading.py", line 870, in run
Mar 18 08:37:39 fish ingestors[29798]:     self._target(*self._args, **self._kwargs)
Mar 18 08:37:39 fish ingestors[29798]:   File "/home/aleph/venvs/ingest-file/lib/python3.7/site-packages/servicelayer/worker.py", line 61, in process
Mar 18 08:37:39 fish ingestors[29798]:     self.handle_safe(task)
Mar 18 08:37:39 fish ingestors[29798]:   File "/home/aleph/venvs/ingest-file/lib/python3.7/site-packages/servicelayer/worker.py", line 33, in handle_safe
Mar 18 08:37:39 fish ingestors[29798]:     self.handle(task)
Mar 18 08:37:39 fish ingestors[29798]:   File "/home/aleph/aleph/services/ingest-file/ingestors/worker.py", line 56, in handle
Mar 18 08:37:39 fish ingestors[29798]:     entity_ids = self._ingest(task)
Mar 18 08:37:39 fish ingestors[29798]:   File "/home/aleph/aleph/services/ingest-file/ingestors/worker.py", line 34, in _ingest
Mar 18 08:37:39 fish ingestors[29798]:     manager.ingest_entity(entity)
Mar 18 08:37:39 fish ingestors[29798]:   File "/home/aleph/aleph/services/ingest-file/ingestors/manager.py", line 133, in ingest_entity
Mar 18 08:37:39 fish ingestors[29798]:     self.ingest(file_path, entity)
Mar 18 08:37:39 fish ingestors[29798]:   File "/home/aleph/aleph/services/ingest-file/ingestors/manager.py", line 147, in ingest
Mar 18 08:37:39 fish ingestors[29798]:     self.delegate(ingestor_class, file_path, entity)
Mar 18 08:37:39 fish ingestors[29798]:   File "/home/aleph/aleph/services/ingest-file/ingestors/manager.py", line 161, in delegate
Mar 18 08:37:39 fish ingestors[29798]:     ingestor_class(self).ingest(file_path, entity)
Mar 18 08:37:39 fish ingestors[29798]:   File "/home/aleph/aleph/services/ingest-file/ingestors/tabular/ods.py", line 67, in ingest
Mar 18 08:37:39 fish ingestors[29798]:     for sheet in doc.spreadsheet.getElementsByType(Table):
Mar 18 08:37:39 fish ingestors[29798]: AttributeError: 'Text' object has no attribute 'getElementsByType'
Mar 18 08:37:39 fish systemd[1]: ingest-file@2.service: Main process exited, code=exited, status=23/n/a
Mar 18 08:37:39 fish systemd[1]: ingest-file@2.service: Failed with result 'exit-code'.
```

**Comment by pudo** [comment]
Can't seem to reproduce this. Can you perhaps help by identifying the version of `odfpy` you are using? `odfpy==1.4.1` is pinned in the requirements, but a different version would perhaps explain this.

**Comment by pudo** [comment]
This really smells like version mismatch. I'm closing it unless someone else can reproduce :/

**Comment by critocrito** [comment]
Apologies for my late reply. I checked the dependency and `pip freeze` tells me `odfpy==1.4.1`. So it must be something else I'm afraid. From the above error message, how can I find the actual `ods` file that caused the problem? Maybe I can run the import manually in order to debug the cause?
