### ISSUE TITLE
Can't add users

### ISSUE THREAD

**Issue by jigsawsecurity** [alephdata/aleph#1325]
Tried to add a users with aleph createuser and got some gibberish and then the docker container actually crashes... 

Not sure why but thought you may want to know that this is occuring. This was a 3.4.2 system that was upgraded to 3.8.9. 
I may end up reinstalling from scratch but I hope not, I really don't want to reingest all of this data. I know you recommend OAuth but in our scenario we are not able to login with OAuth. 

root@aleph:/aleph# aleph createuser -p redacted -n SomeUser user@enlighten.training
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column role.notified_at does not exist
LINE 1: ...ord_digest, role.reset_token AS role_reset_token, role.notif...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/aleph", line 11, in <module>
    load_entry_point('aleph', 'console_scripts', 'aleph')()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/aleph/aleph/manage.py", line 244, in createuser
    role = create_user(email, name, password, is_admin=admin)
  File "/aleph/aleph/logic/roles.py", line 55, in create_user
    email=email, is_admin=is_admin)
  File "/aleph/aleph/model/role.py", line 134, in load_or_create
    role = cls.by_foreign_id(foreign_id)
  File "/aleph/aleph/model/role.py", line 117, in by_foreign_id
    return cls.all().filter_by(foreign_id=foreign_id).first()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3265, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3043, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column role.notified_at does not exist
LINE 1: ...ord_digest, role.reset_token AS role_reset_token, role.notif...
                                                             ^

[SQL: SELECT role.id AS role_id, role.created_at AS role_created_at, role.updated_at AS role_updated_at, role.deleted_at AS role_deleted_at, role.foreign_id AS role_foreign_id, role.name AS role_name, role.email AS role_email, role.api_key AS role_api_key, role.is_admin AS role_is_admin, role.is_muted AS role_is_muted, role.type AS role_type, role.password_digest AS role_password_digest, role.reset_token AS role_reset_token, role.notified_at AS role_notified_at, role.locale AS role_locale
FROM role
WHERE role.deleted_at IS NULL AND role.foreign_id = %(foreign_id_1)s
 LIMIT %(param_1)s]
[parameters: {'foreign_id_1': 'password:user@enlighten.training', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/f405)

**Comment by jigsawsecurity** [comment]
Had to run it a few times but it finally completed.
