### ISSUE TITLE
Search doesn't find a particular name

### ISSUE THREAD

**Issue by haarts** [alephdata/aleph#1412]
First off; I'm really impressed. This is some serious piece of kit. I particularly like the clean Docker setup. 

That being said I have an issue I can't seem to resolve. The search doesn't find matches on a particular name 'Mohammad'. Everything I've searched for so far works fine. For exampl, searching for 'jafari':

![image](https://user-images.githubusercontent.com/10660/96578131-fc49e500-12d4-11eb-8ef8-e101f2025d53.png)

The results show a 'mohammad'. I would expect that searching for 'mohammad' would show this person:

![image](https://user-images.githubusercontent.com/10660/96578271-36b38200-12d5-11eb-8690-72555b73bb35.png)

The odd thing is that it does work for all other first names.

What I did:
- download opensanctions (master)
- download aleph (master)
- run the crawlers in opensanctions
- push 2 datasets to aleph
- login and search

From the issues here I gleaned the reindex command which I tried:

```
root@4e9fbd58fa12:/aleph# aleph reindex-full
[2020-10-20 11:01:40,521] INFO:aleph:[un_sc_sanctions] Starting to re-index
[2020-10-20 11:01:40,551] DEBUG:aleph.logic.collections:[un_sc_sanctions] Aggregating model...
[2020-10-20 11:01:41,526] DEBUG:aleph.logic.collections:[un_sc_sanctions] Index: 1000...
[2020-10-20 11:01:42,638] DEBUG:aleph.logic.collections:[un_sc_sanctions] Index: 2000...
[2020-10-20 11:01:43,780] DEBUG:aleph.logic.collections:[un_sc_sanctions] Indexed 2481 entities
[2020-10-20 11:01:43,980] INFO:aleph.logic.collections:[un_sc_sanctions] Computing statistics...
[2020-10-20 11:01:43,986] ERROR:aleph:Failed to re-index: un_sc_sanctions
Traceback (most recent call last):
  File "/aleph/aleph/manage.py", line 122, in _reindex_collection
    reindex_collection(collection, flush=flush)
  File "/aleph/aleph/logic/collections.py", line 153, in reindex_collection
    compute_collection(collection, force=True)
  File "/aleph/aleph/logic/collections.py", line 88, in compute_collection
    index.update_collection_stats(collection.id)
  File "/aleph/aleph/index/collections.py", line 154, in update_collection_stats
    result = es.search(index=index, body=query, request_timeout=3600, timeout="20m")
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/__init__.py", line 1612, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/base.py", line 300, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [aleph-entity-company-v1]', aleph-entity-company-v1, index_or_alias)
[2020-10-20 11:01:43,989] INFO:aleph:[ch_seco_sanctions] Starting to re-index
[2020-10-20 11:01:44,001] DEBUG:aleph.logic.collections:[ch_seco_sanctions] Aggregating model...
[2020-10-20 11:01:44,392] DEBUG:aleph.logic.collections:[ch_seco_sanctions] Index: 1000...
[2020-10-20 11:01:44,759] DEBUG:aleph.logic.collections:[ch_seco_sanctions] Index: 2000...
[2020-10-20 11:01:45,350] DEBUG:aleph.logic.collections:[ch_seco_sanctions] Index: 3000...
[2020-10-20 11:01:45,814] DEBUG:aleph.logic.collections:[ch_seco_sanctions] Index: 4000...
[2020-10-20 11:01:47,535] DEBUG:aleph.logic.collections:[ch_seco_sanctions] Index: 5000...
[2020-10-20 11:01:48,649] DEBUG:aleph.logic.collections:[ch_seco_sanctions] Index: 6000...
[2020-10-20 11:01:49,473] DEBUG:aleph.logic.collections:[ch_seco_sanctions] Index: 7000...
[2020-10-20 11:01:49,698] DEBUG:aleph.logic.collections:[ch_seco_sanctions] Indexed 7243 entities
[2020-10-20 11:01:49,859] INFO:aleph.logic.collections:[ch_seco_sanctions] Computing statistics...
[2020-10-20 11:01:49,871] ERROR:aleph:Failed to re-index: ch_seco_sanctions
Traceback (most recent call last):
  File "/aleph/aleph/manage.py", line 122, in _reindex_collection
    reindex_collection(collection, flush=flush)
  File "/aleph/aleph/logic/collections.py", line 153, in reindex_collection
    compute_collection(collection, force=True)
  File "/aleph/aleph/logic/collections.py", line 88, in compute_collection
    index.update_collection_stats(collection.id)
  File "/aleph/aleph/index/collections.py", line 154, in update_collection_stats
    result = es.search(index=index, body=query, request_timeout=3600, timeout="20m")
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/client/__init__.py", line 1612, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/connection/base.py", line 300, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [aleph-entity-company-v1]', aleph-entity-company-v1, index_or_alias)
root@4e9fbd58fa12:/aleph# 
```

This fails and the UI is now greeting me with: 

![image](https://user-images.githubusercontent.com/10660/96578737-f99bbf80-12d5-11eb-85d3-1bd7b0f9f226.png)

Looks like I dug myself a hole. Any pointers?

**Comment by pudo** [comment]
The second part of your ticket here refers to running `aleph resetindex`. Run `aleph upgrade` to fix it. The search result thing will be fixed next release.

**Comment by ByUnal** [comment]
@haarts  I also run the crawlers in opensanctions by using instructions in https://github.com/alephdata/opensanctions
But How can I push these datasets to my local Aleph ? 
What should be "ALEPHCLIENT_HOST" for my local ? I tried https://localhost:8080/ but It doesn't work. Can you help me ?

**Comment by haarts** [comment]
@ByUnal you must modify the docker compose files of both opensanctions and aleph. I'm attaching two patches for the respective docker-compose.yaml files.
[aleph.txt](https://github.com/alephdata/aleph/files/5439878/aleph.txt)
[opensanctions.txt](https://github.com/alephdata/aleph/files/5439880/opensanctions.txt)

When you've done that you can enter the worker container of the opensanctions project and export the `ALEPHCLIENT_HOST` env var. For the host name use `aleph` (iirc).

**Comment by ByUnal** [comment]
@haarts Thanks for the feedback. I should copy whole thing inside aleph.txt , then paste into aleph/docker-compose.yaml file right?
Also, I'm going to do same thing for opensanctions/docker-compose.yaml file by using opensanction.txt this time ?

**Comment by haarts** [comment]
No. It's a patch file. Apply like this: `patch docker-compose.ymp opensactions.txt`. On you terminal of course.

**Comment by ByUnal** [comment]
@haarts Okay, Thanks. I'm on it.

**Comment by ByUnal** [comment]
@haarts 
`ftm store iterate -d un_sc_sanctions | alephclient --host {} write-entities -f un_sc_sanctions`
It wants me to write a host URL, I wrote http://localhost:8080/ but It gave me an error. Can you help me on this one too ?

or should I do ? `export ALEPHCLIENT_HOST http://localhost:8080/cases`

**Comment by haarts** [comment]
I don't know if you could better export it. I believe this to be equivalent. 

aleph is running on a different network, not localhost. I can't recall what I did exactly but you need to reach aleph via the network you created in the docker compose file. Something like `http://aleph:8000`. You need to supply a path in that url too iirc... So the final version is `http://aleph:8000/some-path-I-can't-recall`.

Please have a look at the `/etc/hosts` file, that might contain network resolutions. Also try to ping the other network first.

**Comment by pudo** [comment]
Maybe useful to check out the docker documentation on networking a bit, too: https://docs.docker.com/compose/networking/

**Comment by haarts** [comment]
Ah wait. I recall. As the domain name you need to use the name of the docker service. So `api` in this case. Try `ping api`.

**Comment by ByUnal** [comment]
@haarts I tried ping api in my aleph container (entered by using `make shell`), It returns me something like this:
172.XX.X.X
So, What should be my host URL now ? `http://aleph:172.XX.X.X/`

**Comment by haarts** [comment]
`aleph` is the domain name brother... `http://aleph/`. Then you need to figure out what the correct path is.

**Comment by ByUnal** [comment]
It throws me this = `Error: Failed to parse: http://aleph:172.XX.X.X/api/2/collections?filter%3Aforeign_id=un_sc_sanctions`
(Of course I entered a number instead of X, I'm just not sharing it)

**Comment by ByUnal** [comment]
@haarts Sorry, I'm not very good at network things. I hope I will figure out. That is why I bothered you so much.

**Comment by haarts** [comment]
Have a look here: https://docs.alephdata.org/developers/alephclient#configuration It seems to suggest no path is necessary. I can't recall. Please note you have to have an API key too.

**Comment by ByUnal** [comment]
I checked here before, I had an API key, finding it was easy. But I cannot still find `ALEPHCLIENT_HOST` of Aleph which is working on my localhost.
The documentation you shared is not  apprehensible. Where should execute this command `pip install alephclient ` ?
It tells me to do `export ALEPHCLIENT_HOST=https://data.occrp.org/`, but I'm not using this domain. 
It shouldn't be that much complicated, don't you think ?
Please, Direct me in detailed way finding  `ALEPHCLIENT_HOST`. I will be appreciate.

**Comment by haarts** [comment]
This is it: `export ALEPHCLIENT_HOST=http://api:8000` after modifying the docker compose files as described.
