### ISSUE TITLE
UI doesn't build with react-scripts 4.0.0

### ISSUE THREAD

**Issue by ang-st** [alephdata/aleph#1482]
Hi, 
I fetched master and UI doesn't build out of box

```
ui_1                | 
ui_1                | > aleph-ui@3.9.5 start /alephui
ui_1                | > react-scripts start
ui_1                | 
ui_1                | /alephui/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:239
ui_1                |       appTsConfig.compilerOptions[option] = value;
ui_1                |                                           ^
ui_1                | 
ui_1                | TypeError: Cannot assign to read only property 'jsx' of object '#<Object>'
ui_1                |     at verifyTypeScriptSetup (/alephui/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:239:43)
ui_1                |     at Object.<anonymous> (/alephui/node_modules/react-scripts/scripts/start.js:31:1)
ui_1                |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
ui_1                |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
ui_1                |     at Module.load (internal/modules/cjs/loader.js:928:32)
ui_1                |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
ui_1                |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
ui_1                |     at internal/main/run_main_module.js:17:47
```

the quick fix is to upgrade to `"react-scripts": "4.0.1",`

**Comment by pudo** [comment]
cf. f1881a84047559f99be57f79087a0baaca0841f7 ... If I ever meet someone working on webpack, CRA or react, they will have to buy me significant amounts of alcohol to make things OK again.
