### ISSUE TITLE
Fresh install failes with docker-compose run --rm shell aleph upgrade

### ISSUE THREAD

**Issue by oldenstam** [alephdata/aleph#1650]
Hello!

Trying to set up aleph for production and followed steps on  [https://docs.alephdata.org/developers/installation#production-deployment](https://docs.alephdata.org/developers/installation#production-deployment)

When I come to run the command `docker-compose run --rm shell aleph upgrade`
I get error message saying that it is the wrong password for aleph user

`Traceback (most recent call last):
  File "/usr/local/bin/aleph", line 33, in <module>
    sys.exit(load_entry_point('aleph', 'console_scripts', 'aleph')())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/aleph/aleph/manage.py", line 396, in upgrade
    upgrade_system()
  File "/aleph/aleph/migration.py", line 12, in upgrade_system
    flask_migrate.upgrade()
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 271, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/dist-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/dist-packages/alembic/script/base.py", line 481, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/aleph/aleph/migrate/env.py", line 49, in <module>
    run_migrations_online()
  File "/aleph/aleph/migrate/env.py", line 32, in run_migrations_online
    connection = engine.connect()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2263, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 104, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2369, in raw_connection
    return self._wrap_pool_connect(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "aleph"`

And when I check **docker-compose ps -a** it seems that elasticsearch never comes up

`root_api_1                gunicorn -w 6 -b 0.0.0.0:8 ...   Up             8000/tcp
root_convert-document_1   gunicorn -w 4 --bind 0.0.0 ...   Up (healthy)
root_elasticsearch_1      /k8s-entrypoint.sh               Exit 1
root_ingest-file_1        /bin/sh -c ingestors process     Up
root_postgres_1           docker-entrypoint.sh postgres    Up             5432/tcp
root_redis_1              docker-entrypoint.sh redis ...   Up             6379/tcp
root_shell_1              /bin/bash                        Exit 0
root_ui_1                 /docker-entrypoint.sh ngin ...   Up             80/tcp, 0.0.0.0:8080->8080/tcp
root_worker_1             aleph worker                     Up`

Logs for **root_elasticsearch_1**

`docker logs root_elasticsearch_1
ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];
Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
        at java.base/java.nio.file.Files.createDirectory(Files.java:694)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:801)
        at java.base/java.nio.file.Files.createDirectories(Files.java:787)
        at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:274)
        at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:211)
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:271)
        at org.elasticsearch.node.Node.<init>(Node.java:344)
        at org.elasticsearch.node.Node.<init>(Node.java:277)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)`

There is plenty of more logs, pls let me know if it would be helpful and I will post it. 

Would be much appreciated if someone can point me in the right direction :)

**Comment by pudo** [comment]
Not quite sure what's happening here. Are you running this on some very funky platform (Windows, SELinux, Swarm, etc.)? How much RAM is available? I assume the login error with postgres is also a follow-on from some initialisation error that happened earlier. Can you maybe delete the postgres docker volume (`docker volume rm aleph_postgres-data`) and then share the log from the postgres container (`docker-compose logs postgres`)?

**Comment by oldenstam** [comment]
Hello @pudo and thanks for the reply!

Running on CentOS 8 with 8GB of ram on an openstack platform, so not that funky :)
Removing the volume doesn't seem to be possible without running `docker-compose down --volumes` but then, all containers shuts down.

`# docker volume rm root_postgres-data
Error response from daemon: remove root_postgres-data: volume is in use - [ef61e009cb6a6bfb05a42b69084bbafbc3d1d1adb917ff21744bba361c8f17bd]`


The log for postgres:
`postgres_1          | PostgreSQL init process complete; ready for start up.
postgres_1          |
postgres_1          | 2021-02-25 12:11:02.938 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1          | 2021-02-25 12:11:02.938 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1          | 2021-02-25 12:11:02.964 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1          | 2021-02-25 12:11:03.021 UTC [66] LOG:  database system was shut down at 2021-02-25 12:11:02 UTC
postgres_1          | 2021-02-25 12:11:03.039 UTC [1] LOG:  database system is ready to accept connections
postgres_1          | 2021-02-25 12:11:03.607 UTC [73] FATAL:  password authentication failed for user "aleph"
postgres_1          | 2021-02-25 12:11:03.607 UTC [73] DETAIL:  Role "aleph" does not exist.
postgres_1          |   Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1          | 2021-02-25 12:13:27.244 UTC [76] FATAL:  password authentication failed for user "aleph"
postgres_1          | 2021-02-25 12:13:27.244 UTC [76] DETAIL:  Role "aleph" does not exist.
postgres_1          |   Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1          | 2021-02-25 12:15:08.798 UTC [79] FATAL:  password authentication failed for user "aleph"
postgres_1          | 2021-02-25 12:15:08.798 UTC [79] DETAIL:  Role "aleph" does not exist.
postgres_1          |   Connection matched pg_hba.conf line 95: "host all all all md5"`

**Comment by oldenstam** [comment]
An update:

Tried to run from scratch and without running `sudo su` I just ran `sudo docker-compose up -d`
which seemed to make things a little better, because when I ran `docker-compose run --rm shell aleph upgrade` it actually started to upgrade.

The only thing now is that there is a "Failed to establish a new connection" from ElasticSearch
```{"logger": "aleph.core", "timestamp": "2021-03-01 13:54:36.137284", "message": "ElasticSearch error: <urllib3.connection.HTTPConnection object at 0x7f6b51324970>: Failed to establish a new connection: [Errno 111] Connection refused", "severity": "WARNING"}
{"logger": "servicelayer.util", "timestamp": "2021-03-01 13:54:36.137598", "message": "Back-off: 1.99s", "severity": "DEBUG"}
{"logger": "aleph.core", "timestamp": "2021-03-01 13:55:10.163617", "message": "ElasticSearch error: <urllib3.connection.HTTPConnection object at 0x7f6b51336700>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution", "severity": "WARNING"}
{"logger": "servicelayer.util", "timestamp": "2021-03-01 13:55:10.163811", "message": "Back-off: 1.68s", "severity": "DEBUG"}
{"logger": "aleph.core", "timestamp": "2021-03-01 13:55:43.880922", "message": "ElasticSearch error: <urllib3.connection.HTTPConnection object at 0x7f6b51339af0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution", "severity": "WARNING"}
{"logger": "servicelayer.util", "timestamp": "2021-03-01 13:55:43.881114", "message": "Back-off: 1.58s", "severity": "DEBUG"}
{"logger": "aleph.core", "timestamp": "2021-03-01 13:56:17.495873", "message": "ElasticSearch error: <urllib3.connection.HTTPConnection object at 0x7f6b513396d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution", "severity": "WARNING"}
{"logger": "servicelayer.util", "timestamp": "2021-03-01 13:56:17.496074", "message": "Back-off: 2.22s", "severity": "DEBUG"}
{"logger": "aleph.core", "timestamp": "2021-03-01 13:56:51.760912", "message": "ElasticSearch error: <urllib3.connection.HTTPConnection object at 0x7f6b51336520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution", "severity": "WARNING"}
{"logger": "servicelayer.util", "timestamp": "2021-03-01 13:56:51.761092", "message": "Back-off: 3.68s", "severity": "DEBUG"}
```


Which makes sense because ElasticSearch always crash when I ran `docker-compose up -d`

```"Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes",
"at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]",
"at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]",
"at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]",
"at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]",
"at java.nio.file.Files.createDirectory(Files.java:694) ~[?:?]",
"at java.nio.file.Files.createAndCheckIsDirectory(Files.java:801) ~[?:?]",
"at java.nio.file.Files.createDirectories(Files.java:787) ~[?:?]",
"at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:274) ~[elasticsearch-7.9.0.jar:7.9.0]",
"at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:211) ~[elasticsearch-7.9.0.jar:7.9.0]",
"at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:271) ~[elasticsearch-7.9.0.jar:7.9.0]",
"at org.elasticsearch.node.Node.<init>(Node.java:344) ~[elasticsearch-7.9.0.jar:7.9.0]",
"at org.elasticsearch.node.Node.<init>(Node.java:277) ~[elasticsearch-7.9.0.jar:7.9.0]",
"at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227) ~[elasticsearch-7.9.0.jar:7.9.0]",
"at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227) ~[elasticsearch-7.9.0.jar:7.9.0]",
"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.9.0.jar:7.9.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.9.0.jar:7.9.0]",
"... 6 more"] }
uncaught exception in thread [main]
ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];
Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
        at java.base/java.nio.file.Files.createDirectory(Files.java:694)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:801)
        at java.base/java.nio.file.Files.createDirectories(Files.java:787)
        at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:274)
        at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:211)
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:271)
        at org.elasticsearch.node.Node.<init>(Node.java:344)
        at org.elasticsearch.node.Node.<init>(Node.java:277)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
For complete error details, refer to the log at /usr/share/elasticsearch/logs/docker-cluster.log```

**Comment by oldenstam** [comment]
I saw the line **ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];** and it hit me, that maybe there is to little permission set on where it mounts the volumes, so I ran `sudo chmod go+w /data/*` which fixed the problem and I am now up and running :)

**Comment by pudo** [comment]
Oooh ok that’s  makes perfect sense in retrospect. Weird.
