### ISSUE TITLE
PDF Ingestion Failures on data.occrp.org

### ISSUE THREAD

**Issue by DakotaNelson** [alephdata/aleph#177]
```
(u'4 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'record', u'_id': u'8fd22c0bc86142ab6f924ed64c7a18ec9115473b', u'error': {u'index': u'aleph_blue', u'reason': u'routing is required for [aleph_blue]/[record]/[8fd22c0bc86142ab6f924ed64c7a18ec9115473b]', u'type': u'routing_missing_exception'}, u'_index': u'aleph_blue'}}, {u'index': {u'status': 400, u'_type': u'record', u'_id': u'1e639644e9341f575a7b29f2d465ba848fc2196d', u'error': {u'index': u'aleph_blue', u'reason': u'routing is required for [aleph_blue]/[record]/[1e639644e9341f575a7b29f2d465ba848fc2196d]', u'type': u'routing_missing_exception'}, u'_index': u'aleph_blue'}}, {u'index': {u'status': 400, u'_type': u'record', u'_id': u'efe0db84ed4f8a24b7fb2e9e7a50edecb8e47b16', u'error': {u'index': u'aleph_blue', u'reason': u'routing is required for [aleph_blue]/[record]/[efe0db84ed4f8a24b7fb2e9e7a50edecb8e47b16]', u'type': u'routing_missing_exception'}, u'_index': u'aleph_blue'}}, {u'index': {u'status': 400, u'_type': u'record', u'_id': u'a120b636b291ea9856e803386d8ead0c395acb1e', u'error': {u'index': u'aleph_blue', u'reason': u'routing is required for [aleph_blue]/[record]/[a120b636b291ea9856e803386d8ead0c395acb1e]', u'type': u'routing_missing_exception'}, u'_index': u'aleph_blue'}}])
```

```
Traceback (most recent call last):
  File "/aleph/aleph/ingest/ingestor.py", line 121, in dispatch
    best_cls(collection_id).ingest(meta, local_path)
  File "/aleph/aleph/ingest/text.py", line 56, in ingest
    self.extract_pdf(meta, local_path)
  File "/aleph/aleph/ingest/text.py", line 43, in extract_pdf
    self.emit(document)
  File "/aleph/aleph/ingest/ingestor.py", line 42, in emit
    analyze_document(document)
  File "/aleph/aleph/analyze/__init__.py", line 74, in analyze_document
    index_document(document)
  File "/aleph/aleph/index/documents.py", line 39, in index_document
    bulk_op(generate_records(document))
  File "/aleph/aleph/index/util.py", line 11, in bulk_op
    bulk(es, iter, stats_only=True, chunk_size=1000, request_timeout=120.0)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 188, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 160, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 132, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
BulkIndexError: (u'4 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'record', u'_id': u'8fd22c0bc86142ab6f924ed64c7a18ec9115473b', u'error': {u'index': u'aleph_blue', u'reason': u'routing is required for [aleph_blue]/[record]/[8fd22c0bc86142ab6f924ed64c7a18ec9115473b]', u'type': u'routing_missing_exception'}, u'_index': u'aleph_blue'}}, {u'index': {u'status': 400, u'_type': u'record', u'_id': u'1e639644e9341f575a7b29f2d465ba848fc2196d', u'error': {u'index': u'aleph_blue', u'reason': u'routing is required for [aleph_blue]/[record]/[1e639644e9341f575a7b29f2d465ba848fc2196d]', u'type': u'routing_missing_exception'}, u'_index': u'aleph_blue'}}, {u'index': {u'status': 400, u'_type': u'record', u'_id': u'efe0db84ed4f8a24b7fb2e9e7a50edecb8e47b16', u'error': {u'index': u'aleph_blue', u'reason': u'routing is required for [aleph_blue]/[record]/[efe0db84ed4f8a24b7fb2e9e7a50edecb8e47b16]', u'type': u'routing_missing_exception'}, u'_index': u'aleph_blue'}}, {u'index': {u'status': 400, u'_type': u'record', u'_id': u'a120b636b291ea9856e803386d8ead0c395acb1e', u'error': {u'index': u'aleph_blue', u'reason': u'routing is required for [aleph_blue]/[record]/[a120b636b291ea9856e803386d8ead0c395acb1e]', u'type': u'routing_missing_exception'}, u'_index': u'aleph_blue'}}])
```

Not really sure what to make of this, any help appreciated.

**Comment by pudo** [comment]
Ok, a re-index with the new ES mapping is ongoing, at its conclusion this will work again.

**Comment by DakotaNelson** [comment]
Once it's out of maintenance mode I'll try again - thanks for the fix!
