### ISSUE TITLE
Google OAuth with aleph 3.11.0

### ISSUE THREAD

**Issue by thimios** [alephdata/aleph#2036]
I upgraded Aleph from 3.8.9 to 3.11.0

This is the configurations I **used to have** with version **3.8.9** and was working:

```
ALEPH_OAUTH=true
ALEPH_OAUTH_HANDLER=google
ALEPH_OAUTH_KEY=xxxxxxxxxxxxxxxx.apps.googleusercontent.com
ALEPH_OAUTH_SECRET=xxxxxxxxxxxxxxxxxxxxxx
ALEPH_OAUTH_SCOPE=openid email profile
ALEPH_OAUTH_BASE_URL=https://www.googleapis.com/oauth2/v2/
ALEPH_OAUTH_TOKEN_URL=https://www.googleapis.com/oauth2/v4/token
ALEPH_OAUTH_AUTHORIZE_URL=https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent
```

In my .env file **I now have with version 3.11.0** the following configuration:

```
ALEPH_OAUTH=true
ALEPH_OAUTH_METADATA_URL=https://accounts.google.com/.well-known/openid-configuration
ALEPH_OAUTH_KEY=123456789999-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
ALEPH_OAUTH_SECRET=xxxxxxxxxxxxxxxxxxxxxxxx
```
I have removed all other OAUTH related configuration variables. 

In google Cloud Console I have configured an "OAuth 2.0 Client ID" and in "Authorised redirect URIs" I have: "https://sanctions.givve.com/api/2/sessions/callback" which used to work with my previous version of aleph (3.8.9), unlike mentioned in: https://docs.alephdata.org/developers/installation#using-google-oauth ("http://localhost:8080/api/2/sessions/callback/google").

When clicking on "Sign in via OAuth" I get the google dialog to select which google account to login with, but after selecting one, I get redirected to the url:

https://my-domain-name.com/api/2/sessions/callback?state=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&code=4/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20openid%20https://www.googleapis.com/auth/userinfo.email&authuser=1&hd=my-domain.com&prompt=none

Which gives a 500 error.

I the server logs I see:
```
[2021-10-26 12:27:58 +0000] [7] [ERROR] Error handling request /api/2/sessions/callback?state=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&code=4/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20openid%20https://www.googleapis.com/auth/userinfo.email&authuser=1&hd=my-domain.com&prompt=none
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/sync.py", line 136, in handle
     self.handle_request(listener, req, client, addr)
   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/sync.py", line 179, in handle_request
     respiter = self.wsgi(environ, resp.start_response)
 130.211.1.45 - - [26/Oct/2021:12:27:58 +0000] "GET /api/2/sessions/callback?state=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&code=4/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20openid%20https://www.googleapis.com/auth/userinfo.email&authuser=1&hd=my-domain.com&prompt=none HTTP/1.1" 500 141 "https://accounts.google.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2088, in __call__
     return self.wsgi_app(environ, start_response)
   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
     response = self.handle_exception(e)
   File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
     return cors_after_request(app.make_response(f(*args, **kwargs)))
   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2070, in wsgi_app
     response = self.full_dispatch_request()
   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1515, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
     return cors_after_request(app.make_response(f(*args, **kwargs)))
   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1513, in full_dispatch_request
     rv = self.dispatch_request()
   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in dispatch_request
     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
   File "/aleph/aleph/views/sessions_api.py", line 111, in oauth_callback
     role = handle_oauth(oauth.provider, oauth_token)
  File "/aleph/aleph/oauth.py", line 92, in handle_oauth
     for group in _get_groups(provider, oauth_token, token):
   File "/aleph/aleph/oauth.py", line 46, in _get_groups
     access_token = _parse_access_token(provider, oauth_token)
   File "/aleph/aleph/oauth.py", line 41, in _parse_access_token
     return jwt.decode(token, key=load_key, claims_options=claims)
   File "/usr/local/lib/python3.8/dist-packages/authlib/jose/rfc7519/jwt.py", line 103, in decode
     raise DecodeError('Invalid input segments length')
 authlib.jose.errors.DecodeError: Invalid input segments length: 
```

What could I be doing wrong?

**Comment by keanpaderes** [comment]
Hi @thimios! If you're okay with using a modified version of aleph in the meantime for OAuth to work, please refer to this issue #2003  for the fix that we had to implement for our deployment.

**Comment by thimios** [comment]
closing as duplicate of https://github.com/alephdata/aleph/issues/2003
