### ISSUE TITLE
No workers present on fresh docker launch, 'make worker' errors

### ISSUE THREAD

**Issue by straykat914** [alephdata/aleph#2093]
Running a fresh development build of Aleph. 
```make all``` pulls and builds with no noticeable errors.  Web UI loads fine.

Uploading data, I encountered the common 'Stuck at 67%' issue.

Attempted to run ```make worker``` and received this traceback:

```
~/aleph (main) > make worker
docker-compose -f docker-compose.dev.yml up -d --remove-orphans \
        postgres elasticsearch ingest-file \
        convert-document
aleph_convert-document_1 is up-to-date
aleph_redis_1 is up-to-date
aleph_elasticsearch_1 is up-to-date
aleph_postgres_1 is up-to-date
aleph_ingest-file_1 is up-to-date
docker-compose -f docker-compose.dev.yml run -p 127.0.0.1:5679:5679 --rm app python3 -m debugpy --listen 0.0.0.0:5679 /usr/local/bin/aleph worker
Creating aleph_app_run ... done
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/usr/local/lib/python3.8/dist-packages/debugpy/server/cli.py", line 444, in main
    run()
  File "/usr/local/lib/python3.8/dist-packages/debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.8/runpy.py", line 264, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/usr/lib/python3.8/runpy.py", line 234, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/aleph'
ERROR: 1
make: *** [Makefile:30: worker] Error 1
```

**Comment by urchnk** [comment]
@straykat914 I've got the same error. Could you tell me how you resolved it?

**Comment by sunu** [comment]
@urchnk Alternatively you can try running `make shell` and run `aleph worker` in the shell you get. Let me know if that works for you

**Comment by urchnk** [comment]
@sunu It helped, thanks a lot!
