### ISSUE TITLE
aleph flushdeleted returns ForeignKeyViolation

### ISSUE THREAD

**Issue by monneyboi** [alephdata/aleph#2113]
I'm trying to clean up some deleted investigations / documents after i discovered that Aleph does not remove documents from S3 after investigations have been deleted.

I ran `aleph flushdeleted` from one of the workers, but got the following errors.

```
app@aleph-worker-5d4668cf74-b6ctl:/aleph$ aleph flushdeleted
2022-02-02 14:08:12.321082 [info     ] [EntitySetItem]: 68 deleted objects [aleph.model.common]
2022-02-02 14:08:12.329061 [info     ] [EntitySet]: 220 deleted objects [aleph.model.common]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ForeignKeyViolation: update or delete on table "entityset" violates foreign key constraint "entityset_item_entityset_id_fkey" on table "entityset_item"
DETAIL:  Key (id)=(a8b97b9437be401a92c84ae53ff58ef4) is still referenced from table "entityset_item".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/aleph", line 33, in <module>
    sys.exit(load_entry_point('aleph', 'console_scripts', 'aleph')())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 444, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/aleph/aleph/manage.py", line 214, in flushdeleted
    cleanup_deleted()
  File "/aleph/aleph/migration.py", line 23, in cleanup_deleted
    EntitySet.cleanup_deleted()
  File "/aleph/aleph/model/common.py", line 104, in cleanup_deleted
    pq.delete(synchronize_session=False)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3136, in delete
    result = self.session.execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1611, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1478, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2023, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) update or delete on table "entityset" violates foreign key constraint "entityset_item_entityset_id_fkey" on table "entityset_item"
DETAIL:  Key (id)=(a8b97b9437be401a92c84ae53ff58ef4) is still referenced from table "entityset_item".

[SQL: DELETE FROM entityset WHERE entityset.deleted_at IS NOT NULL]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
app@aleph-worker-5d4668cf74-b6ctl:/aleph$ exit
command terminated with exit code 1
```

Am i misunderstanding something or is this a bug?

**Comment by sunu** [comment]
Yes, this looks like a bug. Ideally, the entityset items should have been deleted already. I will see if I can reproduce this issue locally.
