### ISSUE TITLE
Itegrate Okta OAuth w/ Aleph

### ISSUE THREAD

**Issue by m3ck0** [alephdata/aleph#2121]
I'm trying to integrate Aleph w/ Okta (OAuth). I have problem on callback endpoint of Aleph saying: invalid_client: The client secret supplied for a confidential client is invalid. If you have resolved similar issues, can you please help / assist for possible causes? (you can find detailed information below):

What I did:
- created Okta OIDC application
- created Okta authorization server (just for test, before that used default AS)
- created custom authorization server access policy; scope; (for test)
- configured aleph to use authorization server (default / custom) values (in environment):
    - ALEPH_OAUTH
    - ALEPH_OAUTH_KEY
    - ALEPH_OAUTH_SECRET
    - ALEPH_OAUTH_NAME (value is Okta, not sure if this is correct / causes any problem)
    - ALEPH_OAUTH_TOKEN_URL (`https://{domain}.okta.com/oauth2/{auth_server_id}/v1/token`)
    - ALEPH_OAUTH_AUTHORIZE_URL (`https://{domain}.okta.com/oauth2/{auth_server_id}/v1/authorize`)
    - ALEPH_OAUTH_METADATA_URL (`https://{domain}.okta.com/oauth2/{auth_server_id}/.well-known/oauth-authorization-server`)
    - ALEPH_OAUTH_SCOPE (custom_scope same result w/ or w/o this value)

When I try to sign in using OAuth from Aleph:
- I got redirected to the Okta
- signing in to the Okta
- got redirected back to Aleph on `/api/2/sessions/callback?code=***&state=***` endpoint with Internal Server Error

The traceback is similar to this:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/gthread.py", line 323, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/aleph/aleph/views/sessions_api.py", line 106, in oauth_callback
    raise err
  File "/aleph/aleph/views/sessions_api.py", line 103, in oauth_callback
    oauth_token = oauth.provider.authorize_access_token(redirect_uri=uri)
  File "/usr/local/lib/python3.8/dist-packages/authlib/integrations/flask_client/remote_app.py", line 76, in authorize_access_token
    token = self.fetch_access_token(**params)
  File "/usr/local/lib/python3.8/dist-packages/authlib/integrations/base_client/remote_app.py", line 110, in fetch_access_token
    token = client.fetch_token(token_endpoint, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/authlib/oauth2/client.py", line 203, in fetch_token
    return self._fetch_token(
  File "/usr/local/lib/python3.8/dist-packages/authlib/oauth2/client.py", line 226, in _fetch_token
    return self.parse_response_token(resp.json())
  File "/usr/local/lib/python3.8/dist-packages/authlib/oauth2/client.py", line 380, in parse_response_token
    self.handle_error(error, description)
  File "/usr/local/lib/python3.8/dist-packages/authlib/integrations/requests_client/oauth2_session.py", line 117, in handle_error
    raise OAuthError(error_type, error_description)
authlib.integrations.base_client.errors.OAuthError: invalid_client: The client secret supplied for a confidential client is invalid
```

**Comment by sunu** [comment]
Hi @m3ck0, thanks for taking the time to file this issue. I haven't personally tested Aleph's oauth against Okta. But from the error message I assume it's complaining about an invalid client secret.

The client secret is stored in `ALEPH_OAUTH_SECRET` and relevant code that constructs the Oauth client can be found here: https://github.com/alephdata/aleph/blob/ab6ed09412b70de00b489d33b14704e4a811cf00/aleph/oauth.py#L18-L25

I would appreciate if you can take some time to figure out if the arguments being passed in there are correct and match the values expected by Okta. And if you would like to contribute a fix for this issue, I would love to help any way I can.

**Comment by mattcg** [comment]
I think you have a problem with your config. Remove all your ALEPH_OAUTH_* fields and keep these only:

```
    ALEPH_OAUTH_HANDLER: oidc
    ALEPH_OAUTH_KEY: yourkey
    ALEPH_OAUTH_METADATA_URL: >-
      https://okta.your-domain.com/oauth2/general/.well-known/openid-configuration
    ALEPH_OAUTH_SCOPE: openid email profile groups
    ALEPH_OAUTH_TOKEN_METHOD: POST
```

Okta publishes the required URLs to the openid-configuration file. Like that you don't have any of those values littering your configration.

**Comment by m3ck0** [comment]
@mattcg thank you for your feedback about removing spare fields :)
@sunu thanks for the advice, helped me to resolve the issue:

During seeing the OAuth values in the `aleph/aleph/oauth.py`, the secret key was sourced from k8s secrets, instead of environment variables, which had different values (from secrets, dummy value was mounted). Updating the secrets with correct value solved the problem.
