### ISSUE TITLE
Aleph development build fails on Mac M1

### ISSUE THREAD

**Issue by anderser** [alephdata/aleph#2140]
Cloning latest Aleph and running `make build` fails on Apple Mac with M1 chip. Probably due to node-sass compilation problems. 

```
 > [alephdata/aleph-ui:latest  8/12] RUN npm install:
#26 48.35 npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
#26 48.67 npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
#26 48.77 npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
#26 49.74 npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
#26 50.28 npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
#26 50.29 npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
#26 50.43 npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
#26 50.53 npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
#26 50.58 npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
#26 50.65 npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
#26 50.69 npm WARN deprecated har-validator@5.1.5: this library is no longer supported
#26 51.80 npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
#26 53.40 npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
#26 53.45 npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
#26 57.30 npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
#26 58.09 npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
#26 59.40 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
#26 62.00 npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
#26 62.71 npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
#26 65.29 npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
#26 65.36 npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
#26 66.03 npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
#26 70.64 npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
#26 75.50 npm notice
#26 75.50 npm notice New minor version of npm available! 8.3.1 -> 8.5.1
#26 75.50 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.1>
#26 75.50 npm notice Run `npm install -g npm@8.5.1` to update!
#26 75.50 npm notice
#26 75.50 npm ERR! code 1
#26 75.50 npm ERR! path /alephui/node_modules/node-sass
#26 75.50 npm ERR! command failed
#26 75.50 npm ERR! command sh -c node scripts/build.js
#26 75.50 npm ERR! Building: /usr/local/bin/node /alephui/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
#26 75.50 npm ERR! gyp info it worked if it ends with ok
#26 75.50 npm ERR! gyp verb cli [
#26 75.50 npm ERR! gyp verb cli   '/usr/local/bin/node',
#26 75.50 npm ERR! gyp verb cli   '/alephui/node_modules/node-gyp/bin/node-gyp.js',
#26 75.50 npm ERR! gyp verb cli   'rebuild',
#26 75.50 npm ERR! gyp verb cli   '--verbose',
#26 75.50 npm ERR! gyp verb cli   '--libsass_ext=',
#26 75.50 npm ERR! gyp verb cli   '--libsass_cflags=',
#26 75.50 npm ERR! gyp verb cli   '--libsass_ldflags=',
#26 75.50 npm ERR! gyp verb cli   '--libsass_library='
#26 75.50 npm ERR! gyp verb cli ]
#26 75.50 npm ERR! gyp info using node-gyp@8.4.1
#26 75.50 npm ERR! gyp info using node@16.14.0 | linux | arm64
#26 75.50 npm ERR! gyp verb command rebuild []
#26 75.50 npm ERR! gyp verb command clean []
#26 75.50 npm ERR! gyp verb clean removing "build" directory
#26 75.50 npm ERR! gyp verb command configure []
#26 75.50 npm ERR! gyp verb find Python Python is not set from command line or npm configuration
#26 75.50 npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
#26 75.50 npm ERR! gyp verb find Python checking if "python3" can be used
#26 75.50 npm ERR! gyp verb find Python - executing "python3" to get executable path
#26 75.50 npm ERR! gyp verb find Python - "python3" is not in PATH or produced an error
#26 75.50 npm ERR! gyp verb find Python checking if "python" can be used
#26 75.50 npm ERR! gyp verb find Python - executing "python" to get executable path
#26 75.50 npm ERR! gyp verb find Python - executable path is "/usr/bin/python"
#26 75.50 npm ERR! gyp verb find Python - executing "/usr/bin/python" to get version
#26 75.50 npm ERR! gyp verb find Python - version is "2.7.16"
#26 75.50 npm ERR! gyp verb find Python - version is 2.7.16 - should be >=3.6.0
#26 75.50 npm ERR! gyp verb find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
#26 75.50 npm ERR! gyp ERR! find Python
#26 75.50 npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
#26 75.50 npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
#26 75.50 npm ERR! gyp ERR! find Python checking if "python3" can be used
#26 75.50 npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
#26 75.50 npm ERR! gyp ERR! find Python checking if "python" can be used
#26 75.50 npm ERR! gyp ERR! find Python - executable path is "/usr/bin/python"
#26 75.50 npm ERR! gyp ERR! find Python - version is "2.7.16"
#26 75.50 npm ERR! gyp ERR! find Python - version is 2.7.16 - should be >=3.6.0
#26 75.50 npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
#26 75.50 npm ERR! gyp ERR! find Python
#26 75.50 npm ERR! gyp ERR! find Python **********************************************************
#26 75.50 npm ERR! gyp ERR! find Python You need to install the latest version of Python.
#26 75.50 npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#26 75.50 npm ERR! gyp ERR! find Python you can try one of the following options:
#26 75.50 npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#26 75.50 npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
#26 75.50 npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
#26 75.50 npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
#26 75.50 npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#26 75.50 npm ERR! gyp ERR! find Python For more information consult the documentation at:
#26 75.50 npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#26 75.50 npm ERR! gyp ERR! find Python **********************************************************
#26 75.50 npm ERR! gyp ERR! find Python
#26 75.50 npm ERR! gyp ERR! configure error
#26 75.50 npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
#26 75.50 npm ERR! gyp ERR! stack     at PythonFinder.fail (/alephui/node_modules/node-gyp/lib/find-python.js:330:47)
#26 75.50 npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/alephui/node_modules/node-gyp/lib/find-python.js:159:21)
#26 75.50 npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/alephui/node_modules/node-gyp/lib/find-python.js:266:16)
#26 75.50 npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/alephui/node_modules/node-gyp/lib/find-python.js:297:7)
#26 75.50 npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:390:7)
#26 75.50 npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
#26 75.50 npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
#26 75.50 npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
#26 75.50 npm ERR! gyp ERR! System Linux 5.10.76-linuxkit
#26 75.50 npm ERR! gyp ERR! command "/usr/local/bin/node" "/alephui/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
#26 75.50 npm ERR! gyp ERR! cwd /alephui/node_modules/node-sass
#26 75.50 npm ERR! gyp ERR! node -v v16.14.0
#26 75.50 npm ERR! gyp ERR! node-gyp -v v8.4.1
#26 75.50 npm ERR! gyp ERR! not ok
#26 75.50 npm ERR! Build failed with error code: 1
#26 75.50
#26 75.50 npm ERR! A complete log of this run can be found in:
#26 75.50 npm ERR!     /root/.npm/_logs/2022-02-18T09_23_20_934Z-debug-0.log
```

Might be related to this https://sebastix.nl/blog/issue-with-node-sass-in-docker-on-apples-silicon-arm-m1-chipset/ ?

**Comment by anderser** [comment]
Changing to
```"node-sass": "^6.0.0",``` (from 7.0.0) in the package.json of the UI did the trick, but I am not sure if that will impact other UI-functions/sass use?

**Comment by sunu** [comment]
Also node-sass seems to be deprecated: https://github.com/sass/node-sass#node-sass. @Rosencrantz Can you take a look may be?

**Comment by sunu** [comment]
Should be fixed by https://github.com/alephdata/aleph/pull/2145
