### ISSUE TITLE
BUG: network connection error during installation

### ISSUE THREAD

**Issue by reuschling** [alephdata/aleph#2639]
I try to install aleph on my machine. I checked out the git repo with the latest release tag. Then I call `make all`. During installation, I get the following error:
```
 [error    ] ElasticSearch error: <urllib3.connection.HTTPConnection object at 0x7fc1fa490670>: Failed to establish a new connection: [Errno 111] Connection refused [aleph.core] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

```
The installation process runs further, the container will be started. In a different shell, I call 'make worker'. I see a web UI, and I can get a command line with `make shell`. When I try to crawl the testdata with `aleph crawldir /aleph/contrib/testdata` the job will be added to the queue. Nevertheless, with `aleph status`, the job is pending forever and never reaches the running status. Also in the web UI the progressbar never shows any progress.

My assumption was the worker is not there as described in the documentation. I tried to start it alternatively with `aleph worker` in a second shell. But still the jobs are pending.

Now I think there is some issue that the containers can not talk to/see each other. But now I'm stuck

**Aleph version**
latest (3.12.7)
**Additional context**
OS: Arch Linux

**Comment by reuschling** [comment]
When I show into the logs of the containers, I see following error inside `aleph-ingest-file-1`
```
socket.gaierror: [Errno -2] Name or service not known

2022-10-28 14:11:33.086458 [info     ] Worker active, stages: ['analyze', 'ingest'] [ingestors.worker] 

2022-10-28 14:11:33.090304 [info     ] Worker has 16 worker threads.  [servicelayer.taskqueue] 

2022-10-28 14:11:33.150331 [error    ] Address resolution failed: gaierror(-2, 'Name or service not known') [pika.adapters.utils.selector_ioloop_adapter] 

2022-10-28 14:11:33.150788 [error    ] getaddrinfo failed: gaierror(-2, 'Name or service not known'). [pika.adapters.utils.connection_workflow] 

2022-10-28 14:11:33.150995 [error    ] AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name or service not known'); first exception - None. [pika.adapters.utils.connection_workflow] 

2022-10-28 14:11:33.151047 [error    ] AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name or service not known'); first exception - None [pika.adapters.utils.connection_workflow] 

2022-10-28 14:11:33.151119 [error    ] Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name or service not known'); first exception - None [pika.adapters.blocking_connection] 

2022-10-28 14:11:33.151171 [error    ] Error in _create_connection(). [pika.adapters.blocking_connection] 
```

**Comment by tillprochaska** [comment]
Hi @reuschling, you may need to pin the version of the `ingest-file` image in `docker-compose.dev.yml` to 3.16.4. Please see https://github.com/alephdata/aleph/pull/2636 for context.

**Comment by reuschling** [comment]
It works now! Thanks a lot @tillprochaska, you made my day.
