### ISSUE TITLE
BUG: worker thread exits because of self relationship

### ISSUE THREAD

**Issue by brassy-endomorph** [alephdata/aleph#2879]
**Describe the bug**

```
2023-02-10 17:16:47.022867 [error    ] Error in task handling         [servicelayer.worker] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/servicelayer/worker.py", line 40, in handle_safe
    self.handle(task)
  File "/ingestors/ingestors/worker.py", line 48, in handle
    entity_ids = self._ingest(dataset, task)
  File "/ingestors/ingestors/worker.py", line 24, in _ingest
    manager.ingest_entity(entity)
  File "/ingestors/ingestors/manager.py", line 132, in ingest_entity
    self.ingest(file_path, entity)
  File "/ingestors/ingestors/manager.py", line 152, in ingest
    self.finalize(entity)
  File "/ingestors/ingestors/manager.py", line 155, in finalize
    self.emit_entity(entity)
  File "/ingestors/ingestors/manager.py", line 75, in emit_entity
    entity = self.ns.apply(entity)
  File "/usr/local/lib/python3.8/dist-packages/followthemoney/namespace.py", line 106, in apply
    signed.add(prop, self.sign(entity_id))
  File "/usr/local/lib/python3.8/dist-packages/followthemoney/proxy.py", line 193, in add
    value = prop.type.clean(value, proxy=self, fuzzy=fuzzy, format=format)
  File "/usr/local/lib/python3.8/dist-packages/followthemoney/types/entity.py", line 48, in clean
    return self.clean_text(entity_id, fuzzy=fuzzy, format=format, proxy=proxy)
  File "/usr/local/lib/python3.8/dist-packages/followthemoney/types/entity.py", line 62, in clean_text
    raise InvalidData(msg % (proxy.schema, text))
followthemoney.exc.InvalidData: Self-relationship (<Schema('Package')>): [redacted]
```

**To Reproduce**

I don't know. Probably related to #2877 

**Expected behavior**

It doesn't bail? I don't know

**Aleph version**

3.13.0

**Comment by tillprochaska** [comment]
@brassy-endomorph Could you provide an example of a file or entity that triggers this bug when ingested?

**Comment by brassy-endomorph** [comment]
I don't know how to work backwards from the ID to the line/file/etc. that caused it. Can you explain how to do that?
