### ISSUE TITLE
there is no unique or exclusion constraint matching the ON CONFLICT specification

### ISSUE THREAD

**Issue by monneyboi** [alephdata/aleph#3058]
After migrating our Aleph to another cloud, we encountered these errors in the `aleph-worker` logs on re-indexing a specific collection. 

I have not seen these before and googling also does not enlighten me. I was wondering if somebody has seen these before and knows what they mean? Is this a issue in Aleph, an issue in my collection, or does this point to something that somehow got corrupted during our migration? Any pointers would be highly appreciated.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ftmstore/loader.py", line 102, in flush
    self._upsert_values(conn, values)
  File "/usr/local/lib/python3.8/dist-packages/ftmstore/loader.py", line 79, in _upsert_values
    conn.execute(stmt)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidColumnReference) there is no unique or exclusion constraint matching the ON CONFLICT specification
```

**Comment by tillprochaska** [comment]
What Aleph version does your new deployment use?

**Comment by catileptic** [comment]
@monneyboi just wanted to check whether you have zeroed in on a plausible explanation for what happened here. We'd like to try to understand whether this is still a standing issue with the migration process.

**Comment by catileptic** [comment]
@monneyboi I'm closing this, but please feel free to re-open or tag this in a new Issue if you can see this behaviour emerging again
