### ISSUE TITLE
Migrations broken by SQLAlchemy version bump

### ISSUE THREAD

**Issue by monneyboi** [alephdata/aleph#3176]
When resetting my dev environment database and index today resulted in the following error:
```
{"logger": "alembic.runtime.migration", "timestamp": "2023-06-27 11:03:06.010008", "message": "Running upgrade 1519391870a0 -> b3959bf8cc66, Migrate entity IDs and simplify schema.", "severity": "INFO"}
Traceback (most recent call last):
  File "/usr/bin/aleph", line 33, in <module>
    sys.exit(load_entry_point('aleph', 'console_scripts', 'aleph')())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/aleph/aleph/manage.py", line 490, in upgrade
    upgrade_system()
  File "/aleph/aleph/migration.py", line 12, in upgrade_system
    flask_migrate.upgrade()
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 98, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 185, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/dist-packages/alembic/command.py", line 322, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/dist-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/aleph/aleph/migrate/env.py", line 49, in <module>
    run_migrations_online()
  File "/aleph/aleph/migrate/env.py", line 41, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.8/dist-packages/alembic/runtime/environment.py", line 853, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.8/dist-packages/alembic/runtime/migration.py", line 623, in run_migrations
    step.migration_fn(**kw)
  File "/aleph/aleph/migrate/versions/b3959bf8cc66_entity_ids.py", line 22, in upgrade
    meta.reflect()
TypeError: reflect() missing 1 required positional argument: 'bind'
make: *** [Makefile:51: upgrade] Error 1
```

This seems to be caused by the SQLAlchemy version bump

**Comment by stchris** [comment]
Thanks for reporting this @monneyboi . This came from the most recent merge and I'm looking into it.
