### ISSUE TITLE
Adding custom property to Person.yaml results in ingest-file error

### ISSUE THREAD

**Issue by n0kovo** [alephdata/aleph#3325]
**Describe the bug**
I'm trying to add a new property to `Person.yaml`, by cloning the FtM repo, editing the YAML file and setting `FTM_MODEL_PATH` in `aleph.env` to the `schema` directory containing the modified schema files.

When doing so, and running `make all` after cloning the Aleph repo, the `ingest-file` container gives me the following error and reboots in a loop, while the other containers seem to start without errors:

``` console
2023-09-15 16:00:09 Traceback (most recent call last):
2023-09-15 16:00:09   File "/usr/local/bin/ingestors", line 11, in <module>
2023-09-15 16:00:09     load_entry_point('ingest', 'console_scripts', 'ingestors')()
2023-09-15 16:00:09   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
2023-09-15 16:00:09     return get_distribution(dist).load_entry_point(group, name)
2023-09-15 16:00:09   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
2023-09-15 16:00:09     return ep.load()
2023-09-15 16:00:09   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
2023-09-15 16:00:09     return self.resolve()
2023-09-15 16:00:09   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
2023-09-15 16:00:09     module = __import__(self.module_name, fromlist=['__name__'], level=0)
2023-09-15 16:00:09   File "/ingestors/ingestors/cli.py", line 15, in <module>
2023-09-15 16:00:09     from ingestors.analysis import Analyzer
2023-09-15 16:00:09   File "/ingestors/ingestors/analysis/__init__.py", line 12, in <module>
2023-09-15 16:00:09     from ingestors.analysis.extract import extract_entities
2023-09-15 16:00:09   File "/ingestors/ingestors/analysis/extract.py", line 11, in <module>
2023-09-15 16:00:09     from ingestors.analysis.util import TAG_PERSON, TAG_COMPANY
2023-09-15 16:00:09   File "/ingestors/ingestors/analysis/util.py", line 7, in <module>
2023-09-15 16:00:09     TAG_PERSON = ANALYZABLE.get("peopleMentioned")
2023-09-15 16:00:09 AttributeError: 'NoneType' object has no attribute 'get'
```

**To Reproduce**
``` bash
# Clone FtM repo
cd ~/
git clone https://github.com/alephdata/followthemoney.git

# Add example property to Person schema
cat << EOF >> followthemoney/followthemoney/schema/Person.yaml
    libraryCardNumber:
      label: Library card number
      type: identifier
EOF

# Clone Aleph repo
git clone https://github.com/alephdata/aleph.git
cd aleph/

# Set config env vars
cp aleph.env.tmpl aleph.env
sed -i "s/ALEPH_SECRET_KEY=/ALEPH_SECRET_KEY=$(openssl rand -hex 24)/" aleph.env
sed -i "s/ALEPH_SINGLE_USER=false/ALEPH_SINGLE_USER=true/" aleph.env

# Add Docker mount path for modified FtM schema to aleph.env
echo 'FTM_MODEL_PATH=/host/followthemoney/followthemoney/schema' >> aleph.env

make all
```
**Expected behavior**
I expected Aleph to start and let me import my CSV with the custom `libraryCardNumber` property like so:
`ftm map libraryusers.yml | alephclient write-entities -f libraryusers.csv`

**Aleph version**
`3.15.1`
``` console
❯ git --git-dir=aleph/.git rev-parse HEAD
ef26bfe6631e67ed652fcdf99ec0eb866491ee3f

❯ git --git-dir=followthemoney/.git rev-parse HEAD
d01be6ee3897cb253b85e5e458e26aced1d02880
```
I'm using MacOS with `Docker version 24.0.2, build cb74dfc` and `Docker Compose version v2.19.1`

**Comment by tillprochaska** [comment]
Hi @n0kovo, sorry for the late reply! Setting the `FTM_MODEL_PATH` configuration option is the first step, but you also need to make your modified model is available inside of the Docker containers.

If you’re running Aleph locally on your computer using Docker Compose, you can do that by adding an additional volume for the `api`, `ingest-file`, and `worker` services:

```
volumes:
  # other volumes...
  - "./path/on/your/computer:/followthemoney"
```

This will make the contents of `./path/on/your/computer` available at `/followthemoney` inside of the containers. You can then set `FTM_MODEL_PATH=/followthemoney`. Afterwards, stop (`make stop`) and restart (`make web`) Aleph.

We’re currently in the process of updating Aleph’s technical documentation and I’ve added a note to add more documentation about this use case.

Also make sure to read the [note about caveats of modifying](https://followthemoney.tech/docs/custom/#instance-specific-overrides) the model.

For the future, I’d also invite you to check if your use might fall under the eligible use cases listed in our [support policy](https://github.com/alephdata/aleph/blob/develop/SUPPORT.md) -- this would give you access to our Slack community which is a better place to ask questions about setting up Aleph :)

**Comment by tillprochaska** [comment]
I’m closing this issue for now, but please feel free to reopen if this doesn’t solve your problem or if you think this is a bug.
