### ISSUE TITLE
BUG: installation 

### ISSUE THREAD

**Issue by HideNsec** [alephdata/aleph#3568]
https://pastebin.com/Rm0YSgdF error message

**Comment by HideNsec** [comment]
{"logger": "servicelayer.util", "timestamp": "2024-01-15 19:35:11.498466", "message": "Back-off: 28.18s", "severity": "DEBUG"}
Traceback (most recent call last):
  File "/usr/bin/aleph", line 33, in <module>
    sys.exit(load_entry_point('aleph', 'console_scripts', 'aleph')())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 358, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/aleph/aleph/manage.py", line 500, in upgrade
    upgrade_system()
  File "/aleph/aleph/migration.py", line 15, in upgrade_system
    upgrade_search()
  File "/aleph/aleph/index/admin.py", line 15, in upgrade_search
    configure_collections()
  File "/aleph/aleph/index/collections.py", line 77, in configure_collections
    return configure_index(index, mapping, settings)
  File "/aleph/aleph/index/util.py", line 282, in configure_index
    if es.indices.exists(index=index):
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/local.py", line 515, in _get_current_object
    return get_name(local())
  File "/aleph/aleph/core.py", line 170, in get_es
    raise RuntimeError("Could not connect to ElasticSearch")
RuntimeError: Could not connect to ElasticSearch
ERROR: 1
make: *** [Makefile:45: upgrade] Error 1

**Comment by HideNsec** [comment]
Empty ubuntu 22.04.03 LTS
just installed build-essential and apt-utils

**Comment by stchris** [comment]
Hi @HideNsec ! From the logs you sent I understand that Aleph is failing to connect to ElasticSearch.

This doesn't seem to be a bug, but rather a support request. I would kindly ask you to join our Discourse at https://aleph.discourse.group/, create an account and follow up with more details in a new thread in the Support category. I'm closing this issue for now. Thanks for your understanding!
