### ISSUE TITLE
BUG: Ingest containers constantly crashing because of missing tables

### ISSUE THREAD

**Issue by brassy-endomorph** [alephdata/aleph#3872]
**Describe the bug**

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: ingest_cache

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/servicelayer/tags.py", line 102, in set
    self._store_values(conn, row)
  File "/usr/local/lib/python3.8/dist-packages/servicelayer/tags.py", line 70, in _store_values
    conn.execute(stmt)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: ingest_cache
[SQL: INSERT INTO ingest_cache ("key", value, timestamp) VALUES (?, ?, ?)]
[parameters: ('pdf:<redacted>', '"<redacted>"', '<redacted>')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 376, in _close_connection
    self._dialect.do_close(connection)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 707, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140029389158144 and this is thread id 140028832626432.
```

**To Reproduce**

No idea tbh

**Expected behavior**

The container doesn't crash on processing docs.

**Aleph version**

```
$ aleph --version
Python 3.8.10
Flask 2.3.3
Werkzeug 3.0.3
```

**Comment by catileptic** [comment]
Have you recently changed the versions on Aleph, `ingest-file` or any other container image? If you have gone through an upgrade of the Aleph codebase (so, the `app` and `api` containers), have you already tried running `make upgrade`?

**Comment by stchris** [comment]
@brassy-endomorph I think I know what broke here. In the mean time you might get lucky with this workaround: by setting the environment variable `TAGS_DATABASE_URI` for `ingest-file` to `sqlite:///tags.db` you should no longer get this error.

**Comment by brassy-endomorph** [comment]
Initial reaction is "not crashing" but it has been inconsistent and came in waves. I'll try to report back if we keep getting errors, but the first 20 minutes indicate that this fixed something.

**Comment by stchris** [comment]
Another note on this issue: in theory the 3 `ingest-file` settings `TAGS_DATABASE_URI`, `FTM_STORE_URI` and `ALEPH_DATABASE_URI` all default to the same setting (https://github.com/alephdata/ingest-file/blob/bd321ec7524c15a9ec0396a153f5575856e476f8/ingestors/settings.py#L52). If this happens again I'd be interested to hear which version of Aleph causes this and if those settings are changed from their defaults.
