### ISSUE TITLE
Version 2.0.13 cannot be installed due to missing python packages

### ISSUE THREAD

**Issue by Ueland** [alephdata/aleph#425]
Upon starting up aleph with the 2.0.13 release, the aleph2013_worker image will go into restart loop due to a missing python package:

 `ImportError: cannot import name DictReader
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 279, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 503, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 358, in find_app
    sym = imp(app)
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/aleph/aleph/queues.py", line 1, in <module>
    from aleph.core import create_app, celery as app  # noqa
  File "/aleph/aleph/core.py", line 16, in <module>
    from followthemoney import set_model_locale
  File "/usr/local/lib/python2.7/dist-packages/followthemoney/__init__.py", line 3, in <module>
    from followthemoney.model import Model
  File "/usr/local/lib/python2.7/dist-packages/followthemoney/model.py", line 5, in <module>
    from followthemoney.mapping import QueryMapping, get_source
  File "/usr/local/lib/python2.7/dist-packages/followthemoney/mapping/__init__.py", line 2, in <module>
    from followthemoney.mapping.csv import CSVSource
  File "/usr/local/lib/python2.7/dist-packages/followthemoney/mapping/csv.py", line 5, in <module>
    from csv import DictReader
`

**Comment by pudo** [comment]
This error is caused by a mistake in v2.0.13 which did not pin the version of a dependency - `followthemoney` - to be used. This means 2.0.13 is using the latest version of the library, which has since been migrated to Python 3 and uses absolute imports in a way that fails in Python 2.7.

I would recommend using the just-released 2.1.0 instead.
