### ISSUE TITLE
Fresh Install; Unable to Access Portal

### ISSUE THREAD

**Issue by CyberSweatshop** [alephdata/aleph#444]
Ubuntu 18.04 
Aleph 2.1.1 via Docker

After a fresh installation, I run `docker-compose up` and wait for all services to come online. When I attempting to hit the portal, I see the spinning icon and get a 500 error.  In the server logs, I am seeing:
   
```
api_1                | ERROR:aleph:Exception on /api/2/metadata [GET]
api_1                | Traceback (most recent call last):
api_1                |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
api_1                |     context)
api_1                |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
api_1                |     cursor.execute(statement, parameters)
api_1                | psycopg2.ProgrammingError: relation "role" does not exist
api_1                | LINE 2: FROM role 
api_1                |              ^
api_1                | 
api_1                | 
api_1                | The above exception was the direct cause of the following exception:
api_1                | 
api_1                | Traceback (most recent call last):
api_1                |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1988, in wsgi_app
api_1                |     response = self.full_dispatch_request()
api_1                |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1641, in full_dispatch_request
api_1                |     rv = self.handle_user_exception(e)
api_1                |   File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
api_1                |     return cors_after_request(app.make_response(f(*args, **kwargs)))
api_1                |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1544, in handle_user_exception
api_1                |     reraise(exc_type, exc_value, tb)
api_1                |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
api_1                |     raise value
api_1                |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1637, in full_dispatch_request
api_1                |     rv = self.preprocess_request()
api_1                |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1837, in preprocess_request
api_1                |     rv = func()
api_1                |   File "/aleph/aleph/views/sessions_api.py", line 46, in load_role
api_1                |     request.authz = authz or Authz.from_role(role=None)
api_1                |   File "/aleph/aleph/authz.py", line 29, in from_role
api_1                |     roles = set([Role.load_id(Role.SYSTEM_GUEST)])
api_1                |   File "/aleph/aleph/model/role.py", line 146, in load_id
api_1                |     role = cls.by_foreign_id(foreign_id)
api_1                |   File "/aleph/aleph/model/role.py", line 86, in by_foreign_id
api_1                |     return cls.all().filter_by(foreign_id=foreign_id).first()
api_1                |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2825, in first
api_1                |     ret = list(self[0:1])
api_1                |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2617, in __getitem__
api_1                |     return list(res)
api_1                |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2925, in __iter__
api_1                |     return self._execute_and_instances(context)
api_1                |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2948, in _execute_and_instances
api_1                |     result = conn.execute(querycontext.statement, self._params)
api_1                |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
api_1                |     return meth(self, multiparams, params)
api_1                |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
api_1                |     return connection._execute_clauseelement(self, multiparams, params)
api_1                |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
api_1                |     compiled_sql, distilled_params
api_1                |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
api_1                |     context)
api_1                |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
api_1                |     exc_info
api_1                |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
api_1                |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
api_1                |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
api_1                |     raise value.with_traceback(tb)
api_1                |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
api_1                |     context)
api_1                |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
api_1                |     cursor.execute(statement, parameters)
api_1                | sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "role" does not exist
api_1                | LINE 2: FROM role 
api_1                |              ^
api_1                |  [SQL: 'SELECT role.id AS role_id, role.created_at AS role_created_at, role.updated_at AS role_updated_at, role.deleted_at AS role_deleted_at, role.foreign_id AS role_foreign_id, role.name AS role_name, role.email AS role_email, role.api_key AS role_api_key, role.is_admin AS role_is_admin, role.type AS role_type, role.password_digest AS role_password_digest, role.reset_token AS role_reset_token, role.notified_at AS role_notified_at \nFROM role \nWHERE role.deleted_at IS NULL AND role.foreign_id = %(foreign_id_1)s \n LIMIT %(param_1)s'] [parameters: {'foreign_id_1': 'guest', 'param_1': 1}] (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by Ueland** [comment]
I believe i got the same issue, solved it by creating a user, Check the "Users" section: https://github.com/alephdata/aleph/wiki/Developer-setup

**Comment by CyberSweatshop** [comment]
I was real hopeful and it made sense... After running the create command, I get back the similar error:  
```
raceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: relation "role" does not exist
LINE 2: FROM role 
```

**Comment by CyberSweatshop** [comment]
I've gone back over the directions, I know I am missing something dumb on my end.  Example output from running `aleph collections`. It's like I am missing a database setup...  
  
```
root@a288c89d9e0b:/aleph# aleph collections
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: relation "collection" does not exist
LINE 2: FROM collection 
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/aleph", line 11, in <module>
    load_entry_point('aleph', 'console_scripts', 'aleph')()
  File "/aleph/aleph/manage.py", line 203, in main
    manager.run()
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/aleph/aleph/manage.py", line 50, in collections
    for collection in Collection.all():
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2925, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2948, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "collection" does not exist
LINE 2: FROM collection 
             ^
 [SQL: 'SELECT collection.id AS collection_id, collection.created_at AS collection_created_at, collection.updated_at AS collection_updated_at, collection.deleted_at AS collection_deleted_at, collection.label AS collection_label, collection.summary AS collection_summary, collection.category AS collection_category, collection.countries AS collection_countries, collection.languages AS collection_languages, collection.foreign_id AS collection_foreign_id, collection.publisher AS collection_publisher, collection.publisher_url AS collection_publisher_url, collection.info_url AS collection_info_url, collection.data_url AS collection_data_url, collection.casefile AS collection_casefile, collection.creator_id AS collection_creator_id \nFROM collection \nWHERE collection.deleted_at IS NULL'] (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by pudo** [comment]
Have you run ``aleph upgrade``? It's the command to create the search index and database schema and need to be run at least once before starting any of the other commands.
