### ISSUE TITLE
New production install failing

### ISSUE THREAD

**Issue by winers1290** [alephdata/aleph#514]
Hi all,

Trying to build the latest stable release (2.1.0). The docker build process is fine, but when I try to migrate the database to populate it, I get the following error:

````
root@fe182b3f3831:/aleph# aleph upgrade
INFO:aleph.model:Beginning database migration...
INFO:alembic.runtime.migration:Context impl PostgresqlImpl.
INFO:alembic.runtime.migration:Will assume transactional DDL.
INFO:alembic.runtime.migration:Running upgrade  -> 57e9e4ff269b, init migrations
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: type "role_type" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/aleph", line 11, in <module>
    load_entry_point('aleph', 'console_scripts', 'aleph')()
  File "/aleph/aleph/manage.py", line 202, in main
    manager.run()
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/aleph/aleph/manage.py", line 188, in upgrade
    upgrade_db()
  File "/aleph/aleph/model/__init__.py", line 28, in upgrade_db
    flask_migrate.upgrade()
  File "/usr/local/lib/python3.6/site-packages/flask_migrate/__init__.py", line 235, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.6/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 397, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.6/site-packages/alembic/util/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/aleph/aleph/migrate/env.py", line 46, in <module>
    run_migrations_online()
  File "/aleph/aleph/migrate/env.py", line 39, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.6/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.6/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
    step.migration_fn(**kw)
  File "/aleph/aleph/migrate/versions/57e9e4ff269b_init_migrations.py", line 38, in upgrade
    sa.UniqueConstraint('foreign_id')
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/usr/local/lib/python3.6/site-packages/alembic/operations/ops.py", line 1098, in create_table
    return operations.invoke(op)
  File "/usr/local/lib/python3.6/site-packages/alembic/operations/base.py", line 318, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.6/site-packages/alembic/operations/toimpl.py", line 101, in create_table
    operations.impl.create_table(table)
  File "/usr/local/lib/python3.6/site-packages/alembic/ddl/impl.py", line 193, in create_table
    _ddl_runner=self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 284, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 559, in __call__
    return getattr(self.target, self.name)(*arg, **kw)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1096, in _on_table_create
    t._on_table_create(target, bind, **kw)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py", line 1354, in _on_table_create
    self.create(bind=bind, checkfirst=checkfirst)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py", line 1302, in create
    bind.execute(CreateEnumType(self))
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) type "role_type" already exists
 [SQL: "CREATE TYPE role_type AS ENUM ('user', 'group', 'system')"] (Background on this error at: http://sqlalche.me/e/f405)
````

Any advice? When I deployed the previous stable version (2.0.3), I was getting HTTP 500 error until I was able to run this command. 

With this build, I am getting error "No such index".

**Comment by pudo** [comment]
That sounds like it's cancelled out during a previous upgrade and now has some issues creating the tables. If you can run ``make shell`` and then ``aleph evilshit``, everything should be returned to null and nothing. Then try ``aleph upgrade`` again.

**Comment by winers1290** [comment]
...And that is indeed what happened! Thanks. I did cancel the `aleph evilshit` command at one stage, but this was because it got caught in a loop or something and wasn't completing after about 10 minutes.

Unrelated question - with the `followthemoney` integration, if I were to fork the repository and add/edit the entities, how would I go about updating the `aleph` deployment to include the new library?

I love what this application is doing, but I'd like to see if I can make it more relevant for cyber crime investigations, and at the moment the entities defined within `followthemoney` simply don't intend to tackle that - but I think the use of the model system in general is really useful, so I'd like to customise it if possible.

**Comment by pudo** [comment]
We've been somewhat careful to make it so that the vast majority of ``followthemoney`` entities could be swapped out, except for the basic types like ``Document``, ``Thing``, etc.

If we want to make it configurable, I'd implement that via an environment variable that's read [here](https://github.com/alephdata/followthemoney/blob/master/followthemoney/__init__.py#L9) and can be used to define a different schema base directory. If you only want to add schemata, I think it would be cool to continue loading the "factory defaults" as well.

I'm actually also interested to see if we should include a few ... erm ... cyber entities in the main schema. 

Shall we make this a separate ticket?
